# Generated by Django 6.0 on 2025-12-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ratting',
            new_name='ratings',
        ),
    ]
